### PR TITLE
Add stubs for GamerPresence and LeaderboardReader.PageStart

### PR DESCRIPTION
**Pull request by Hector47**
Add support for Hasta La Muerte

### CODE REVIEW

**Comment by Hector47** [comment]
Tested on Windows

**Comment by mediaexplorer74** [comment]
> Hasta La Muerte

Did you improved the original WPR? Nice. Sounds great!
Please provide the url (link) for Hasta La Muerte xap for desktop gaming via your fork ))

**Comment by Hector47** [comment]
Will do another pull request with only the compatibility changes

**Comment by mediaexplorer74** [comment]
> Will do another pull request with only the compatibility changes

ok.  8212369/WPR repo seems to be inactive. I subscribed to [Hector47/WPR](https://github.com/Hector47/WPR).
Oh, i noticed that you planning to create WPR site based on xemu template. Super!

**Pull request closed without merging**
